export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_ITEM_CART = "DELETE_ITEM_CART"
export const UPDATE_QUANTITY_CART = "UPDATE_QUANTITY_CART"
export const UPDATE_TOTAL_CART = "UPDATE_TOTAL_CART"

